on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    with:
      node-version: '12'
      cache: 'yarn'
  - run: yarn
  - run: yarn test
